project_id = "lfxxokngvbqnkcxvmynp"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322

[studio]
enabled = true
port = 54323

[inbucket]
enabled = true
port = 54324

[storage]
enabled = true
port = 54325

[auth]
enabled = true
port = 54326

[functions.voice-to-text]
verify_jwt = false

[functions.text-to-voice]
verify_jwt = false

[functions.mistral-analysis]
verify_jwt = false

[functions.ai-assistant]
verify_jwt = false