// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lfxxokngvbqnkcxvmynp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxmeHhva25ndmJxbmtjeHZteW5wIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgyMjYyMDIsImV4cCI6MjA3MzgwMjIwMn0.WSN5kf7fsfXe5seKHp372tTwWs6k6lwEA4C9LjD9fVs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});